# LXC
#
#

com.liferay.lxc.dxp.domains=liferay:8080
com.liferay.lxc.dxp.mainDomain=liferay:8080
com.liferay.lxc.dxp.server.protocol=http


#
# langchain ollama
#
langchain4j.ollama.chat-model.base-url=http://ollama:11434
langchain4j.ollama.streaming-chat-model.base-url=http://ollama:11434
